spring.application.name=studenterp


spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ERP?allowPublicKeyRetrieval=true&useSSL=false}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update       
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect



supabase.s3.endpoint=${SUPABASE_S3_ENDPOINT}
supabase.s3.access-key=${SUPABASE_S3_ACCESS_KEY}
supabase.s3.secret-key=${SUPABASE_S3_SECRET_KEY}
supabase.s3.region=${SUPABASE_S3_REGION}
supabase.s3.bucket-name=${SUPABASE_S3_BUCKET_NAME}

spring.jackson.deserialization.fail-on-null-for-primitives=false